// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/kornilova_l/protos/tree.proto

package com.github.kornilova_l.protos;

public final class TreeProtos {
  private TreeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TreeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.kornilova_l.protos.Tree)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 duration = 1;</code>
     */
    long getDuration();

    /**
     * <pre>
     * only for trees which save original call structure
     * </pre>
     *
     * <code>int64 startTime = 2;</code>
     */
    long getStartTime();

    /**
     * <pre>
     * only for trees which save original call structure
     * </pre>
     *
     * <code>int64 threadId = 3;</code>
     */
    long getThreadId();

    /**
     * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
     */
    java.util.List<com.github.kornilova_l.protos.TreeProtos.Tree.Call> 
        getCallsList();
    /**
     * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
     */
    com.github.kornilova_l.protos.TreeProtos.Tree.Call getCalls(int index);
    /**
     * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
     */
    int getCallsCount();
    /**
     * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
     */
    java.util.List<? extends com.github.kornilova_l.protos.TreeProtos.Tree.CallOrBuilder> 
        getCallsOrBuilderList();
    /**
     * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
     */
    com.github.kornilova_l.protos.TreeProtos.Tree.CallOrBuilder getCallsOrBuilder(
        int index);

    /**
     * <code>uint32 depth = 5;</code>
     */
    int getDepth();
  }
  /**
   * Protobuf type {@code com.github.kornilova_l.protos.Tree}
   */
  public  static final class Tree extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.kornilova_l.protos.Tree)
      TreeOrBuilder {
    // Use Tree.newBuilder() to construct.
    private Tree(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tree() {
      duration_ = 0L;
      startTime_ = 0L;
      threadId_ = 0L;
      calls_ = java.util.Collections.emptyList();
      depth_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Tree(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              duration_ = input.readInt64();
              break;
            }
            case 16: {

              startTime_ = input.readInt64();
              break;
            }
            case 24: {

              threadId_ = input.readInt64();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                calls_ = new java.util.ArrayList<com.github.kornilova_l.protos.TreeProtos.Tree.Call>();
                mutable_bitField0_ |= 0x00000008;
              }
              calls_.add(
                  input.readMessage(com.github.kornilova_l.protos.TreeProtos.Tree.Call.parser(), extensionRegistry));
              break;
            }
            case 40: {

              depth_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          calls_ = java.util.Collections.unmodifiableList(calls_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.kornilova_l.protos.TreeProtos.internal_static_com_github_kornilova_l_protos_Tree_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.kornilova_l.protos.TreeProtos.internal_static_com_github_kornilova_l_protos_Tree_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.kornilova_l.protos.TreeProtos.Tree.class, com.github.kornilova_l.protos.TreeProtos.Tree.Builder.class);
    }

    public interface CallOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.github.kornilova_l.protos.Tree.Call)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int64 duration = 1;</code>
       */
      long getDuration();

      /**
       * <code>.com.github.kornilova_l.protos.Event.Enter enter = 2;</code>
       */
      boolean hasEnter();
      /**
       * <code>.com.github.kornilova_l.protos.Event.Enter enter = 2;</code>
       */
      com.github.kornilova_l.protos.EventProtos.Event.Enter getEnter();
      /**
       * <code>.com.github.kornilova_l.protos.Event.Enter enter = 2;</code>
       */
      com.github.kornilova_l.protos.EventProtos.Event.EnterOrBuilder getEnterOrBuilder();

      /**
       * <code>.com.github.kornilova_l.protos.Event.Exit exit = 3;</code>
       */
      com.github.kornilova_l.protos.EventProtos.Event.Exit getExit();
      /**
       * <code>.com.github.kornilova_l.protos.Event.Exit exit = 3;</code>
       */
      com.github.kornilova_l.protos.EventProtos.Event.ExitOrBuilder getExitOrBuilder();

      /**
       * <code>.com.github.kornilova_l.protos.Event.Exception exception = 4;</code>
       */
      com.github.kornilova_l.protos.EventProtos.Event.Exception getException();
      /**
       * <code>.com.github.kornilova_l.protos.Event.Exception exception = 4;</code>
       */
      com.github.kornilova_l.protos.EventProtos.Event.ExceptionOrBuilder getExceptionOrBuilder();

      /**
       * <pre>
       * only for trees which save original call structure
       * </pre>
       *
       * <code>int64 startTime = 5;</code>
       */
      long getStartTime();

      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
       */
      java.util.List<com.github.kornilova_l.protos.TreeProtos.Tree.Call> 
          getCallsList();
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
       */
      com.github.kornilova_l.protos.TreeProtos.Tree.Call getCalls(int index);
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
       */
      int getCallsCount();
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
       */
      java.util.List<? extends com.github.kornilova_l.protos.TreeProtos.Tree.CallOrBuilder> 
          getCallsOrBuilderList();
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
       */
      com.github.kornilova_l.protos.TreeProtos.Tree.CallOrBuilder getCallsOrBuilder(
          int index);

      public com.github.kornilova_l.protos.TreeProtos.Tree.Call.ExitInfoCase getExitInfoCase();
    }
    /**
     * Protobuf type {@code com.github.kornilova_l.protos.Tree.Call}
     */
    public  static final class Call extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.github.kornilova_l.protos.Tree.Call)
        CallOrBuilder {
      // Use Call.newBuilder() to construct.
      private Call(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Call() {
        duration_ = 0L;
        startTime_ = 0L;
        calls_ = java.util.Collections.emptyList();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Call(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                duration_ = input.readInt64();
                break;
              }
              case 18: {
                com.github.kornilova_l.protos.EventProtos.Event.Enter.Builder subBuilder = null;
                if (enter_ != null) {
                  subBuilder = enter_.toBuilder();
                }
                enter_ = input.readMessage(com.github.kornilova_l.protos.EventProtos.Event.Enter.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(enter_);
                  enter_ = subBuilder.buildPartial();
                }

                break;
              }
              case 26: {
                com.github.kornilova_l.protos.EventProtos.Event.Exit.Builder subBuilder = null;
                if (exitInfoCase_ == 3) {
                  subBuilder = ((com.github.kornilova_l.protos.EventProtos.Event.Exit) exitInfo_).toBuilder();
                }
                exitInfo_ =
                    input.readMessage(com.github.kornilova_l.protos.EventProtos.Event.Exit.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((com.github.kornilova_l.protos.EventProtos.Event.Exit) exitInfo_);
                  exitInfo_ = subBuilder.buildPartial();
                }
                exitInfoCase_ = 3;
                break;
              }
              case 34: {
                com.github.kornilova_l.protos.EventProtos.Event.Exception.Builder subBuilder = null;
                if (exitInfoCase_ == 4) {
                  subBuilder = ((com.github.kornilova_l.protos.EventProtos.Event.Exception) exitInfo_).toBuilder();
                }
                exitInfo_ =
                    input.readMessage(com.github.kornilova_l.protos.EventProtos.Event.Exception.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((com.github.kornilova_l.protos.EventProtos.Event.Exception) exitInfo_);
                  exitInfo_ = subBuilder.buildPartial();
                }
                exitInfoCase_ = 4;
                break;
              }
              case 40: {

                startTime_ = input.readInt64();
                break;
              }
              case 50: {
                if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                  calls_ = new java.util.ArrayList<com.github.kornilova_l.protos.TreeProtos.Tree.Call>();
                  mutable_bitField0_ |= 0x00000020;
                }
                calls_.add(
                    input.readMessage(com.github.kornilova_l.protos.TreeProtos.Tree.Call.parser(), extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
            calls_ = java.util.Collections.unmodifiableList(calls_);
          }
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.kornilova_l.protos.TreeProtos.internal_static_com_github_kornilova_l_protos_Tree_Call_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.kornilova_l.protos.TreeProtos.internal_static_com_github_kornilova_l_protos_Tree_Call_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.kornilova_l.protos.TreeProtos.Tree.Call.class, com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder.class);
      }

      private int bitField0_;
      private int exitInfoCase_ = 0;
      private java.lang.Object exitInfo_;
      public enum ExitInfoCase
          implements com.google.protobuf.Internal.EnumLite {
        EXIT(3),
        EXCEPTION(4),
        EXITINFO_NOT_SET(0);
        private final int value;
        private ExitInfoCase(int value) {
          this.value = value;
        }
        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static ExitInfoCase valueOf(int value) {
          return forNumber(value);
        }

        public static ExitInfoCase forNumber(int value) {
          switch (value) {
            case 3: return EXIT;
            case 4: return EXCEPTION;
            case 0: return EXITINFO_NOT_SET;
            default: return null;
          }
        }
        public int getNumber() {
          return this.value;
        }
      };

      public ExitInfoCase
      getExitInfoCase() {
        return ExitInfoCase.forNumber(
            exitInfoCase_);
      }

      public static final int DURATION_FIELD_NUMBER = 1;
      private long duration_;
      /**
       * <code>int64 duration = 1;</code>
       */
      public long getDuration() {
        return duration_;
      }

      public static final int ENTER_FIELD_NUMBER = 2;
      private com.github.kornilova_l.protos.EventProtos.Event.Enter enter_;
      /**
       * <code>.com.github.kornilova_l.protos.Event.Enter enter = 2;</code>
       */
      public boolean hasEnter() {
        return enter_ != null;
      }
      /**
       * <code>.com.github.kornilova_l.protos.Event.Enter enter = 2;</code>
       */
      public com.github.kornilova_l.protos.EventProtos.Event.Enter getEnter() {
        return enter_ == null ? com.github.kornilova_l.protos.EventProtos.Event.Enter.getDefaultInstance() : enter_;
      }
      /**
       * <code>.com.github.kornilova_l.protos.Event.Enter enter = 2;</code>
       */
      public com.github.kornilova_l.protos.EventProtos.Event.EnterOrBuilder getEnterOrBuilder() {
        return getEnter();
      }

      public static final int EXIT_FIELD_NUMBER = 3;
      /**
       * <code>.com.github.kornilova_l.protos.Event.Exit exit = 3;</code>
       */
      public com.github.kornilova_l.protos.EventProtos.Event.Exit getExit() {
        if (exitInfoCase_ == 3) {
           return (com.github.kornilova_l.protos.EventProtos.Event.Exit) exitInfo_;
        }
        return com.github.kornilova_l.protos.EventProtos.Event.Exit.getDefaultInstance();
      }
      /**
       * <code>.com.github.kornilova_l.protos.Event.Exit exit = 3;</code>
       */
      public com.github.kornilova_l.protos.EventProtos.Event.ExitOrBuilder getExitOrBuilder() {
        if (exitInfoCase_ == 3) {
           return (com.github.kornilova_l.protos.EventProtos.Event.Exit) exitInfo_;
        }
        return com.github.kornilova_l.protos.EventProtos.Event.Exit.getDefaultInstance();
      }

      public static final int EXCEPTION_FIELD_NUMBER = 4;
      /**
       * <code>.com.github.kornilova_l.protos.Event.Exception exception = 4;</code>
       */
      public com.github.kornilova_l.protos.EventProtos.Event.Exception getException() {
        if (exitInfoCase_ == 4) {
           return (com.github.kornilova_l.protos.EventProtos.Event.Exception) exitInfo_;
        }
        return com.github.kornilova_l.protos.EventProtos.Event.Exception.getDefaultInstance();
      }
      /**
       * <code>.com.github.kornilova_l.protos.Event.Exception exception = 4;</code>
       */
      public com.github.kornilova_l.protos.EventProtos.Event.ExceptionOrBuilder getExceptionOrBuilder() {
        if (exitInfoCase_ == 4) {
           return (com.github.kornilova_l.protos.EventProtos.Event.Exception) exitInfo_;
        }
        return com.github.kornilova_l.protos.EventProtos.Event.Exception.getDefaultInstance();
      }

      public static final int STARTTIME_FIELD_NUMBER = 5;
      private long startTime_;
      /**
       * <pre>
       * only for trees which save original call structure
       * </pre>
       *
       * <code>int64 startTime = 5;</code>
       */
      public long getStartTime() {
        return startTime_;
      }

      public static final int CALLS_FIELD_NUMBER = 6;
      private java.util.List<com.github.kornilova_l.protos.TreeProtos.Tree.Call> calls_;
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
       */
      public java.util.List<com.github.kornilova_l.protos.TreeProtos.Tree.Call> getCallsList() {
        return calls_;
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
       */
      public java.util.List<? extends com.github.kornilova_l.protos.TreeProtos.Tree.CallOrBuilder> 
          getCallsOrBuilderList() {
        return calls_;
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
       */
      public int getCallsCount() {
        return calls_.size();
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
       */
      public com.github.kornilova_l.protos.TreeProtos.Tree.Call getCalls(int index) {
        return calls_.get(index);
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
       */
      public com.github.kornilova_l.protos.TreeProtos.Tree.CallOrBuilder getCallsOrBuilder(
          int index) {
        return calls_.get(index);
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (duration_ != 0L) {
          output.writeInt64(1, duration_);
        }
        if (enter_ != null) {
          output.writeMessage(2, getEnter());
        }
        if (exitInfoCase_ == 3) {
          output.writeMessage(3, (com.github.kornilova_l.protos.EventProtos.Event.Exit) exitInfo_);
        }
        if (exitInfoCase_ == 4) {
          output.writeMessage(4, (com.github.kornilova_l.protos.EventProtos.Event.Exception) exitInfo_);
        }
        if (startTime_ != 0L) {
          output.writeInt64(5, startTime_);
        }
        for (int i = 0; i < calls_.size(); i++) {
          output.writeMessage(6, calls_.get(i));
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (duration_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, duration_);
        }
        if (enter_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, getEnter());
        }
        if (exitInfoCase_ == 3) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, (com.github.kornilova_l.protos.EventProtos.Event.Exit) exitInfo_);
        }
        if (exitInfoCase_ == 4) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, (com.github.kornilova_l.protos.EventProtos.Event.Exception) exitInfo_);
        }
        if (startTime_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(5, startTime_);
        }
        for (int i = 0; i < calls_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, calls_.get(i));
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.github.kornilova_l.protos.TreeProtos.Tree.Call)) {
          return super.equals(obj);
        }
        com.github.kornilova_l.protos.TreeProtos.Tree.Call other = (com.github.kornilova_l.protos.TreeProtos.Tree.Call) obj;

        boolean result = true;
        result = result && (getDuration()
            == other.getDuration());
        result = result && (hasEnter() == other.hasEnter());
        if (hasEnter()) {
          result = result && getEnter()
              .equals(other.getEnter());
        }
        result = result && (getStartTime()
            == other.getStartTime());
        result = result && getCallsList()
            .equals(other.getCallsList());
        result = result && getExitInfoCase().equals(
            other.getExitInfoCase());
        if (!result) return false;
        switch (exitInfoCase_) {
          case 3:
            result = result && getExit()
                .equals(other.getExit());
            break;
          case 4:
            result = result && getException()
                .equals(other.getException());
            break;
          case 0:
          default:
        }
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + DURATION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getDuration());
        if (hasEnter()) {
          hash = (37 * hash) + ENTER_FIELD_NUMBER;
          hash = (53 * hash) + getEnter().hashCode();
        }
        hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStartTime());
        if (getCallsCount() > 0) {
          hash = (37 * hash) + CALLS_FIELD_NUMBER;
          hash = (53 * hash) + getCallsList().hashCode();
        }
        switch (exitInfoCase_) {
          case 3:
            hash = (37 * hash) + EXIT_FIELD_NUMBER;
            hash = (53 * hash) + getExit().hashCode();
            break;
          case 4:
            hash = (37 * hash) + EXCEPTION_FIELD_NUMBER;
            hash = (53 * hash) + getException().hashCode();
            break;
          case 0:
          default:
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.github.kornilova_l.protos.TreeProtos.Tree.Call parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.github.kornilova_l.protos.TreeProtos.Tree.Call parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.github.kornilova_l.protos.TreeProtos.Tree.Call parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.github.kornilova_l.protos.TreeProtos.Tree.Call parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.github.kornilova_l.protos.TreeProtos.Tree.Call parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.github.kornilova_l.protos.TreeProtos.Tree.Call parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.github.kornilova_l.protos.TreeProtos.Tree.Call parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.github.kornilova_l.protos.TreeProtos.Tree.Call parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.github.kornilova_l.protos.TreeProtos.Tree.Call parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.github.kornilova_l.protos.TreeProtos.Tree.Call parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.github.kornilova_l.protos.TreeProtos.Tree.Call parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.github.kornilova_l.protos.TreeProtos.Tree.Call parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.github.kornilova_l.protos.TreeProtos.Tree.Call prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.github.kornilova_l.protos.Tree.Call}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.github.kornilova_l.protos.Tree.Call)
          com.github.kornilova_l.protos.TreeProtos.Tree.CallOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.github.kornilova_l.protos.TreeProtos.internal_static_com_github_kornilova_l_protos_Tree_Call_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.github.kornilova_l.protos.TreeProtos.internal_static_com_github_kornilova_l_protos_Tree_Call_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.github.kornilova_l.protos.TreeProtos.Tree.Call.class, com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder.class);
        }

        // Construct using com.github.kornilova_l.protos.TreeProtos.Tree.Call.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
            getCallsFieldBuilder();
          }
        }
        public Builder clear() {
          super.clear();
          duration_ = 0L;

          if (enterBuilder_ == null) {
            enter_ = null;
          } else {
            enter_ = null;
            enterBuilder_ = null;
          }
          startTime_ = 0L;

          if (callsBuilder_ == null) {
            calls_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            callsBuilder_.clear();
          }
          exitInfoCase_ = 0;
          exitInfo_ = null;
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.github.kornilova_l.protos.TreeProtos.internal_static_com_github_kornilova_l_protos_Tree_Call_descriptor;
        }

        public com.github.kornilova_l.protos.TreeProtos.Tree.Call getDefaultInstanceForType() {
          return com.github.kornilova_l.protos.TreeProtos.Tree.Call.getDefaultInstance();
        }

        public com.github.kornilova_l.protos.TreeProtos.Tree.Call build() {
          com.github.kornilova_l.protos.TreeProtos.Tree.Call result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.github.kornilova_l.protos.TreeProtos.Tree.Call buildPartial() {
          com.github.kornilova_l.protos.TreeProtos.Tree.Call result = new com.github.kornilova_l.protos.TreeProtos.Tree.Call(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          result.duration_ = duration_;
          if (enterBuilder_ == null) {
            result.enter_ = enter_;
          } else {
            result.enter_ = enterBuilder_.build();
          }
          if (exitInfoCase_ == 3) {
            if (exitBuilder_ == null) {
              result.exitInfo_ = exitInfo_;
            } else {
              result.exitInfo_ = exitBuilder_.build();
            }
          }
          if (exitInfoCase_ == 4) {
            if (exceptionBuilder_ == null) {
              result.exitInfo_ = exitInfo_;
            } else {
              result.exitInfo_ = exceptionBuilder_.build();
            }
          }
          result.startTime_ = startTime_;
          if (callsBuilder_ == null) {
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
              calls_ = java.util.Collections.unmodifiableList(calls_);
              bitField0_ = (bitField0_ & ~0x00000020);
            }
            result.calls_ = calls_;
          } else {
            result.calls_ = callsBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          result.exitInfoCase_ = exitInfoCase_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.github.kornilova_l.protos.TreeProtos.Tree.Call) {
            return mergeFrom((com.github.kornilova_l.protos.TreeProtos.Tree.Call)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.github.kornilova_l.protos.TreeProtos.Tree.Call other) {
          if (other == com.github.kornilova_l.protos.TreeProtos.Tree.Call.getDefaultInstance()) return this;
          if (other.getDuration() != 0L) {
            setDuration(other.getDuration());
          }
          if (other.hasEnter()) {
            mergeEnter(other.getEnter());
          }
          if (other.getStartTime() != 0L) {
            setStartTime(other.getStartTime());
          }
          if (callsBuilder_ == null) {
            if (!other.calls_.isEmpty()) {
              if (calls_.isEmpty()) {
                calls_ = other.calls_;
                bitField0_ = (bitField0_ & ~0x00000020);
              } else {
                ensureCallsIsMutable();
                calls_.addAll(other.calls_);
              }
              onChanged();
            }
          } else {
            if (!other.calls_.isEmpty()) {
              if (callsBuilder_.isEmpty()) {
                callsBuilder_.dispose();
                callsBuilder_ = null;
                calls_ = other.calls_;
                bitField0_ = (bitField0_ & ~0x00000020);
                callsBuilder_ = 
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                     getCallsFieldBuilder() : null;
              } else {
                callsBuilder_.addAllMessages(other.calls_);
              }
            }
          }
          switch (other.getExitInfoCase()) {
            case EXIT: {
              mergeExit(other.getExit());
              break;
            }
            case EXCEPTION: {
              mergeException(other.getException());
              break;
            }
            case EXITINFO_NOT_SET: {
              break;
            }
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.github.kornilova_l.protos.TreeProtos.Tree.Call parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.github.kornilova_l.protos.TreeProtos.Tree.Call) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int exitInfoCase_ = 0;
        private java.lang.Object exitInfo_;
        public ExitInfoCase
            getExitInfoCase() {
          return ExitInfoCase.forNumber(
              exitInfoCase_);
        }

        public Builder clearExitInfo() {
          exitInfoCase_ = 0;
          exitInfo_ = null;
          onChanged();
          return this;
        }

        private int bitField0_;

        private long duration_ ;
        /**
         * <code>int64 duration = 1;</code>
         */
        public long getDuration() {
          return duration_;
        }
        /**
         * <code>int64 duration = 1;</code>
         */
        public Builder setDuration(long value) {
          
          duration_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 duration = 1;</code>
         */
        public Builder clearDuration() {
          
          duration_ = 0L;
          onChanged();
          return this;
        }

        private com.github.kornilova_l.protos.EventProtos.Event.Enter enter_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
            com.github.kornilova_l.protos.EventProtos.Event.Enter, com.github.kornilova_l.protos.EventProtos.Event.Enter.Builder, com.github.kornilova_l.protos.EventProtos.Event.EnterOrBuilder> enterBuilder_;
        /**
         * <code>.com.github.kornilova_l.protos.Event.Enter enter = 2;</code>
         */
        public boolean hasEnter() {
          return enterBuilder_ != null || enter_ != null;
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Enter enter = 2;</code>
         */
        public com.github.kornilova_l.protos.EventProtos.Event.Enter getEnter() {
          if (enterBuilder_ == null) {
            return enter_ == null ? com.github.kornilova_l.protos.EventProtos.Event.Enter.getDefaultInstance() : enter_;
          } else {
            return enterBuilder_.getMessage();
          }
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Enter enter = 2;</code>
         */
        public Builder setEnter(com.github.kornilova_l.protos.EventProtos.Event.Enter value) {
          if (enterBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            enter_ = value;
            onChanged();
          } else {
            enterBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Enter enter = 2;</code>
         */
        public Builder setEnter(
            com.github.kornilova_l.protos.EventProtos.Event.Enter.Builder builderForValue) {
          if (enterBuilder_ == null) {
            enter_ = builderForValue.build();
            onChanged();
          } else {
            enterBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Enter enter = 2;</code>
         */
        public Builder mergeEnter(com.github.kornilova_l.protos.EventProtos.Event.Enter value) {
          if (enterBuilder_ == null) {
            if (enter_ != null) {
              enter_ =
                com.github.kornilova_l.protos.EventProtos.Event.Enter.newBuilder(enter_).mergeFrom(value).buildPartial();
            } else {
              enter_ = value;
            }
            onChanged();
          } else {
            enterBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Enter enter = 2;</code>
         */
        public Builder clearEnter() {
          if (enterBuilder_ == null) {
            enter_ = null;
            onChanged();
          } else {
            enter_ = null;
            enterBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Enter enter = 2;</code>
         */
        public com.github.kornilova_l.protos.EventProtos.Event.Enter.Builder getEnterBuilder() {
          
          onChanged();
          return getEnterFieldBuilder().getBuilder();
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Enter enter = 2;</code>
         */
        public com.github.kornilova_l.protos.EventProtos.Event.EnterOrBuilder getEnterOrBuilder() {
          if (enterBuilder_ != null) {
            return enterBuilder_.getMessageOrBuilder();
          } else {
            return enter_ == null ?
                com.github.kornilova_l.protos.EventProtos.Event.Enter.getDefaultInstance() : enter_;
          }
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Enter enter = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            com.github.kornilova_l.protos.EventProtos.Event.Enter, com.github.kornilova_l.protos.EventProtos.Event.Enter.Builder, com.github.kornilova_l.protos.EventProtos.Event.EnterOrBuilder> 
            getEnterFieldBuilder() {
          if (enterBuilder_ == null) {
            enterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                com.github.kornilova_l.protos.EventProtos.Event.Enter, com.github.kornilova_l.protos.EventProtos.Event.Enter.Builder, com.github.kornilova_l.protos.EventProtos.Event.EnterOrBuilder>(
                    getEnter(),
                    getParentForChildren(),
                    isClean());
            enter_ = null;
          }
          return enterBuilder_;
        }

        private com.google.protobuf.SingleFieldBuilderV3<
            com.github.kornilova_l.protos.EventProtos.Event.Exit, com.github.kornilova_l.protos.EventProtos.Event.Exit.Builder, com.github.kornilova_l.protos.EventProtos.Event.ExitOrBuilder> exitBuilder_;
        /**
         * <code>.com.github.kornilova_l.protos.Event.Exit exit = 3;</code>
         */
        public com.github.kornilova_l.protos.EventProtos.Event.Exit getExit() {
          if (exitBuilder_ == null) {
            if (exitInfoCase_ == 3) {
              return (com.github.kornilova_l.protos.EventProtos.Event.Exit) exitInfo_;
            }
            return com.github.kornilova_l.protos.EventProtos.Event.Exit.getDefaultInstance();
          } else {
            if (exitInfoCase_ == 3) {
              return exitBuilder_.getMessage();
            }
            return com.github.kornilova_l.protos.EventProtos.Event.Exit.getDefaultInstance();
          }
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Exit exit = 3;</code>
         */
        public Builder setExit(com.github.kornilova_l.protos.EventProtos.Event.Exit value) {
          if (exitBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            exitInfo_ = value;
            onChanged();
          } else {
            exitBuilder_.setMessage(value);
          }
          exitInfoCase_ = 3;
          return this;
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Exit exit = 3;</code>
         */
        public Builder setExit(
            com.github.kornilova_l.protos.EventProtos.Event.Exit.Builder builderForValue) {
          if (exitBuilder_ == null) {
            exitInfo_ = builderForValue.build();
            onChanged();
          } else {
            exitBuilder_.setMessage(builderForValue.build());
          }
          exitInfoCase_ = 3;
          return this;
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Exit exit = 3;</code>
         */
        public Builder mergeExit(com.github.kornilova_l.protos.EventProtos.Event.Exit value) {
          if (exitBuilder_ == null) {
            if (exitInfoCase_ == 3 &&
                exitInfo_ != com.github.kornilova_l.protos.EventProtos.Event.Exit.getDefaultInstance()) {
              exitInfo_ = com.github.kornilova_l.protos.EventProtos.Event.Exit.newBuilder((com.github.kornilova_l.protos.EventProtos.Event.Exit) exitInfo_)
                  .mergeFrom(value).buildPartial();
            } else {
              exitInfo_ = value;
            }
            onChanged();
          } else {
            if (exitInfoCase_ == 3) {
              exitBuilder_.mergeFrom(value);
            }
            exitBuilder_.setMessage(value);
          }
          exitInfoCase_ = 3;
          return this;
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Exit exit = 3;</code>
         */
        public Builder clearExit() {
          if (exitBuilder_ == null) {
            if (exitInfoCase_ == 3) {
              exitInfoCase_ = 0;
              exitInfo_ = null;
              onChanged();
            }
          } else {
            if (exitInfoCase_ == 3) {
              exitInfoCase_ = 0;
              exitInfo_ = null;
            }
            exitBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Exit exit = 3;</code>
         */
        public com.github.kornilova_l.protos.EventProtos.Event.Exit.Builder getExitBuilder() {
          return getExitFieldBuilder().getBuilder();
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Exit exit = 3;</code>
         */
        public com.github.kornilova_l.protos.EventProtos.Event.ExitOrBuilder getExitOrBuilder() {
          if ((exitInfoCase_ == 3) && (exitBuilder_ != null)) {
            return exitBuilder_.getMessageOrBuilder();
          } else {
            if (exitInfoCase_ == 3) {
              return (com.github.kornilova_l.protos.EventProtos.Event.Exit) exitInfo_;
            }
            return com.github.kornilova_l.protos.EventProtos.Event.Exit.getDefaultInstance();
          }
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Exit exit = 3;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            com.github.kornilova_l.protos.EventProtos.Event.Exit, com.github.kornilova_l.protos.EventProtos.Event.Exit.Builder, com.github.kornilova_l.protos.EventProtos.Event.ExitOrBuilder> 
            getExitFieldBuilder() {
          if (exitBuilder_ == null) {
            if (!(exitInfoCase_ == 3)) {
              exitInfo_ = com.github.kornilova_l.protos.EventProtos.Event.Exit.getDefaultInstance();
            }
            exitBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                com.github.kornilova_l.protos.EventProtos.Event.Exit, com.github.kornilova_l.protos.EventProtos.Event.Exit.Builder, com.github.kornilova_l.protos.EventProtos.Event.ExitOrBuilder>(
                    (com.github.kornilova_l.protos.EventProtos.Event.Exit) exitInfo_,
                    getParentForChildren(),
                    isClean());
            exitInfo_ = null;
          }
          exitInfoCase_ = 3;
          onChanged();;
          return exitBuilder_;
        }

        private com.google.protobuf.SingleFieldBuilderV3<
            com.github.kornilova_l.protos.EventProtos.Event.Exception, com.github.kornilova_l.protos.EventProtos.Event.Exception.Builder, com.github.kornilova_l.protos.EventProtos.Event.ExceptionOrBuilder> exceptionBuilder_;
        /**
         * <code>.com.github.kornilova_l.protos.Event.Exception exception = 4;</code>
         */
        public com.github.kornilova_l.protos.EventProtos.Event.Exception getException() {
          if (exceptionBuilder_ == null) {
            if (exitInfoCase_ == 4) {
              return (com.github.kornilova_l.protos.EventProtos.Event.Exception) exitInfo_;
            }
            return com.github.kornilova_l.protos.EventProtos.Event.Exception.getDefaultInstance();
          } else {
            if (exitInfoCase_ == 4) {
              return exceptionBuilder_.getMessage();
            }
            return com.github.kornilova_l.protos.EventProtos.Event.Exception.getDefaultInstance();
          }
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Exception exception = 4;</code>
         */
        public Builder setException(com.github.kornilova_l.protos.EventProtos.Event.Exception value) {
          if (exceptionBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            exitInfo_ = value;
            onChanged();
          } else {
            exceptionBuilder_.setMessage(value);
          }
          exitInfoCase_ = 4;
          return this;
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Exception exception = 4;</code>
         */
        public Builder setException(
            com.github.kornilova_l.protos.EventProtos.Event.Exception.Builder builderForValue) {
          if (exceptionBuilder_ == null) {
            exitInfo_ = builderForValue.build();
            onChanged();
          } else {
            exceptionBuilder_.setMessage(builderForValue.build());
          }
          exitInfoCase_ = 4;
          return this;
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Exception exception = 4;</code>
         */
        public Builder mergeException(com.github.kornilova_l.protos.EventProtos.Event.Exception value) {
          if (exceptionBuilder_ == null) {
            if (exitInfoCase_ == 4 &&
                exitInfo_ != com.github.kornilova_l.protos.EventProtos.Event.Exception.getDefaultInstance()) {
              exitInfo_ = com.github.kornilova_l.protos.EventProtos.Event.Exception.newBuilder((com.github.kornilova_l.protos.EventProtos.Event.Exception) exitInfo_)
                  .mergeFrom(value).buildPartial();
            } else {
              exitInfo_ = value;
            }
            onChanged();
          } else {
            if (exitInfoCase_ == 4) {
              exceptionBuilder_.mergeFrom(value);
            }
            exceptionBuilder_.setMessage(value);
          }
          exitInfoCase_ = 4;
          return this;
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Exception exception = 4;</code>
         */
        public Builder clearException() {
          if (exceptionBuilder_ == null) {
            if (exitInfoCase_ == 4) {
              exitInfoCase_ = 0;
              exitInfo_ = null;
              onChanged();
            }
          } else {
            if (exitInfoCase_ == 4) {
              exitInfoCase_ = 0;
              exitInfo_ = null;
            }
            exceptionBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Exception exception = 4;</code>
         */
        public com.github.kornilova_l.protos.EventProtos.Event.Exception.Builder getExceptionBuilder() {
          return getExceptionFieldBuilder().getBuilder();
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Exception exception = 4;</code>
         */
        public com.github.kornilova_l.protos.EventProtos.Event.ExceptionOrBuilder getExceptionOrBuilder() {
          if ((exitInfoCase_ == 4) && (exceptionBuilder_ != null)) {
            return exceptionBuilder_.getMessageOrBuilder();
          } else {
            if (exitInfoCase_ == 4) {
              return (com.github.kornilova_l.protos.EventProtos.Event.Exception) exitInfo_;
            }
            return com.github.kornilova_l.protos.EventProtos.Event.Exception.getDefaultInstance();
          }
        }
        /**
         * <code>.com.github.kornilova_l.protos.Event.Exception exception = 4;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            com.github.kornilova_l.protos.EventProtos.Event.Exception, com.github.kornilova_l.protos.EventProtos.Event.Exception.Builder, com.github.kornilova_l.protos.EventProtos.Event.ExceptionOrBuilder> 
            getExceptionFieldBuilder() {
          if (exceptionBuilder_ == null) {
            if (!(exitInfoCase_ == 4)) {
              exitInfo_ = com.github.kornilova_l.protos.EventProtos.Event.Exception.getDefaultInstance();
            }
            exceptionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                com.github.kornilova_l.protos.EventProtos.Event.Exception, com.github.kornilova_l.protos.EventProtos.Event.Exception.Builder, com.github.kornilova_l.protos.EventProtos.Event.ExceptionOrBuilder>(
                    (com.github.kornilova_l.protos.EventProtos.Event.Exception) exitInfo_,
                    getParentForChildren(),
                    isClean());
            exitInfo_ = null;
          }
          exitInfoCase_ = 4;
          onChanged();;
          return exceptionBuilder_;
        }

        private long startTime_ ;
        /**
         * <pre>
         * only for trees which save original call structure
         * </pre>
         *
         * <code>int64 startTime = 5;</code>
         */
        public long getStartTime() {
          return startTime_;
        }
        /**
         * <pre>
         * only for trees which save original call structure
         * </pre>
         *
         * <code>int64 startTime = 5;</code>
         */
        public Builder setStartTime(long value) {
          
          startTime_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * only for trees which save original call structure
         * </pre>
         *
         * <code>int64 startTime = 5;</code>
         */
        public Builder clearStartTime() {
          
          startTime_ = 0L;
          onChanged();
          return this;
        }

        private java.util.List<com.github.kornilova_l.protos.TreeProtos.Tree.Call> calls_ =
          java.util.Collections.emptyList();
        private void ensureCallsIsMutable() {
          if (!((bitField0_ & 0x00000020) == 0x00000020)) {
            calls_ = new java.util.ArrayList<com.github.kornilova_l.protos.TreeProtos.Tree.Call>(calls_);
            bitField0_ |= 0x00000020;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.kornilova_l.protos.TreeProtos.Tree.Call, com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder, com.github.kornilova_l.protos.TreeProtos.Tree.CallOrBuilder> callsBuilder_;

        /**
         * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
         */
        public java.util.List<com.github.kornilova_l.protos.TreeProtos.Tree.Call> getCallsList() {
          if (callsBuilder_ == null) {
            return java.util.Collections.unmodifiableList(calls_);
          } else {
            return callsBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
         */
        public int getCallsCount() {
          if (callsBuilder_ == null) {
            return calls_.size();
          } else {
            return callsBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
         */
        public com.github.kornilova_l.protos.TreeProtos.Tree.Call getCalls(int index) {
          if (callsBuilder_ == null) {
            return calls_.get(index);
          } else {
            return callsBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
         */
        public Builder setCalls(
            int index, com.github.kornilova_l.protos.TreeProtos.Tree.Call value) {
          if (callsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureCallsIsMutable();
            calls_.set(index, value);
            onChanged();
          } else {
            callsBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
         */
        public Builder setCalls(
            int index, com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder builderForValue) {
          if (callsBuilder_ == null) {
            ensureCallsIsMutable();
            calls_.set(index, builderForValue.build());
            onChanged();
          } else {
            callsBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
         */
        public Builder addCalls(com.github.kornilova_l.protos.TreeProtos.Tree.Call value) {
          if (callsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureCallsIsMutable();
            calls_.add(value);
            onChanged();
          } else {
            callsBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
         */
        public Builder addCalls(
            int index, com.github.kornilova_l.protos.TreeProtos.Tree.Call value) {
          if (callsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureCallsIsMutable();
            calls_.add(index, value);
            onChanged();
          } else {
            callsBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
         */
        public Builder addCalls(
            com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder builderForValue) {
          if (callsBuilder_ == null) {
            ensureCallsIsMutable();
            calls_.add(builderForValue.build());
            onChanged();
          } else {
            callsBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
         */
        public Builder addCalls(
            int index, com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder builderForValue) {
          if (callsBuilder_ == null) {
            ensureCallsIsMutable();
            calls_.add(index, builderForValue.build());
            onChanged();
          } else {
            callsBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
         */
        public Builder addAllCalls(
            java.lang.Iterable<? extends com.github.kornilova_l.protos.TreeProtos.Tree.Call> values) {
          if (callsBuilder_ == null) {
            ensureCallsIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, calls_);
            onChanged();
          } else {
            callsBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
         */
        public Builder clearCalls() {
          if (callsBuilder_ == null) {
            calls_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000020);
            onChanged();
          } else {
            callsBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
         */
        public Builder removeCalls(int index) {
          if (callsBuilder_ == null) {
            ensureCallsIsMutable();
            calls_.remove(index);
            onChanged();
          } else {
            callsBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
         */
        public com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder getCallsBuilder(
            int index) {
          return getCallsFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
         */
        public com.github.kornilova_l.protos.TreeProtos.Tree.CallOrBuilder getCallsOrBuilder(
            int index) {
          if (callsBuilder_ == null) {
            return calls_.get(index);  } else {
            return callsBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
         */
        public java.util.List<? extends com.github.kornilova_l.protos.TreeProtos.Tree.CallOrBuilder> 
             getCallsOrBuilderList() {
          if (callsBuilder_ != null) {
            return callsBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(calls_);
          }
        }
        /**
         * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
         */
        public com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder addCallsBuilder() {
          return getCallsFieldBuilder().addBuilder(
              com.github.kornilova_l.protos.TreeProtos.Tree.Call.getDefaultInstance());
        }
        /**
         * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
         */
        public com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder addCallsBuilder(
            int index) {
          return getCallsFieldBuilder().addBuilder(
              index, com.github.kornilova_l.protos.TreeProtos.Tree.Call.getDefaultInstance());
        }
        /**
         * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 6;</code>
         */
        public java.util.List<com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder> 
             getCallsBuilderList() {
          return getCallsFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.kornilova_l.protos.TreeProtos.Tree.Call, com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder, com.github.kornilova_l.protos.TreeProtos.Tree.CallOrBuilder> 
            getCallsFieldBuilder() {
          if (callsBuilder_ == null) {
            callsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                com.github.kornilova_l.protos.TreeProtos.Tree.Call, com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder, com.github.kornilova_l.protos.TreeProtos.Tree.CallOrBuilder>(
                    calls_,
                    ((bitField0_ & 0x00000020) == 0x00000020),
                    getParentForChildren(),
                    isClean());
            calls_ = null;
          }
          return callsBuilder_;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:com.github.kornilova_l.protos.Tree.Call)
      }

      // @@protoc_insertion_point(class_scope:com.github.kornilova_l.protos.Tree.Call)
      private static final com.github.kornilova_l.protos.TreeProtos.Tree.Call DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.github.kornilova_l.protos.TreeProtos.Tree.Call();
      }

      public static com.github.kornilova_l.protos.TreeProtos.Tree.Call getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Call>
          PARSER = new com.google.protobuf.AbstractParser<Call>() {
        public Call parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Call(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Call> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Call> getParserForType() {
        return PARSER;
      }

      public com.github.kornilova_l.protos.TreeProtos.Tree.Call getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int DURATION_FIELD_NUMBER = 1;
    private long duration_;
    /**
     * <code>int64 duration = 1;</code>
     */
    public long getDuration() {
      return duration_;
    }

    public static final int STARTTIME_FIELD_NUMBER = 2;
    private long startTime_;
    /**
     * <pre>
     * only for trees which save original call structure
     * </pre>
     *
     * <code>int64 startTime = 2;</code>
     */
    public long getStartTime() {
      return startTime_;
    }

    public static final int THREADID_FIELD_NUMBER = 3;
    private long threadId_;
    /**
     * <pre>
     * only for trees which save original call structure
     * </pre>
     *
     * <code>int64 threadId = 3;</code>
     */
    public long getThreadId() {
      return threadId_;
    }

    public static final int CALLS_FIELD_NUMBER = 4;
    private java.util.List<com.github.kornilova_l.protos.TreeProtos.Tree.Call> calls_;
    /**
     * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
     */
    public java.util.List<com.github.kornilova_l.protos.TreeProtos.Tree.Call> getCallsList() {
      return calls_;
    }
    /**
     * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
     */
    public java.util.List<? extends com.github.kornilova_l.protos.TreeProtos.Tree.CallOrBuilder> 
        getCallsOrBuilderList() {
      return calls_;
    }
    /**
     * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
     */
    public int getCallsCount() {
      return calls_.size();
    }
    /**
     * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
     */
    public com.github.kornilova_l.protos.TreeProtos.Tree.Call getCalls(int index) {
      return calls_.get(index);
    }
    /**
     * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
     */
    public com.github.kornilova_l.protos.TreeProtos.Tree.CallOrBuilder getCallsOrBuilder(
        int index) {
      return calls_.get(index);
    }

    public static final int DEPTH_FIELD_NUMBER = 5;
    private int depth_;
    /**
     * <code>uint32 depth = 5;</code>
     */
    public int getDepth() {
      return depth_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (duration_ != 0L) {
        output.writeInt64(1, duration_);
      }
      if (startTime_ != 0L) {
        output.writeInt64(2, startTime_);
      }
      if (threadId_ != 0L) {
        output.writeInt64(3, threadId_);
      }
      for (int i = 0; i < calls_.size(); i++) {
        output.writeMessage(4, calls_.get(i));
      }
      if (depth_ != 0) {
        output.writeUInt32(5, depth_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (duration_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, duration_);
      }
      if (startTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, startTime_);
      }
      if (threadId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, threadId_);
      }
      for (int i = 0; i < calls_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, calls_.get(i));
      }
      if (depth_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, depth_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.kornilova_l.protos.TreeProtos.Tree)) {
        return super.equals(obj);
      }
      com.github.kornilova_l.protos.TreeProtos.Tree other = (com.github.kornilova_l.protos.TreeProtos.Tree) obj;

      boolean result = true;
      result = result && (getDuration()
          == other.getDuration());
      result = result && (getStartTime()
          == other.getStartTime());
      result = result && (getThreadId()
          == other.getThreadId());
      result = result && getCallsList()
          .equals(other.getCallsList());
      result = result && (getDepth()
          == other.getDepth());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DURATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDuration());
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartTime());
      hash = (37 * hash) + THREADID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getThreadId());
      if (getCallsCount() > 0) {
        hash = (37 * hash) + CALLS_FIELD_NUMBER;
        hash = (53 * hash) + getCallsList().hashCode();
      }
      hash = (37 * hash) + DEPTH_FIELD_NUMBER;
      hash = (53 * hash) + getDepth();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.kornilova_l.protos.TreeProtos.Tree parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.kornilova_l.protos.TreeProtos.Tree parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.kornilova_l.protos.TreeProtos.Tree parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.kornilova_l.protos.TreeProtos.Tree parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.kornilova_l.protos.TreeProtos.Tree parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.kornilova_l.protos.TreeProtos.Tree parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.kornilova_l.protos.TreeProtos.Tree parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.kornilova_l.protos.TreeProtos.Tree parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.kornilova_l.protos.TreeProtos.Tree parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.kornilova_l.protos.TreeProtos.Tree parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.kornilova_l.protos.TreeProtos.Tree parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.kornilova_l.protos.TreeProtos.Tree parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.kornilova_l.protos.TreeProtos.Tree prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.kornilova_l.protos.Tree}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.kornilova_l.protos.Tree)
        com.github.kornilova_l.protos.TreeProtos.TreeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.kornilova_l.protos.TreeProtos.internal_static_com_github_kornilova_l_protos_Tree_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.kornilova_l.protos.TreeProtos.internal_static_com_github_kornilova_l_protos_Tree_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.kornilova_l.protos.TreeProtos.Tree.class, com.github.kornilova_l.protos.TreeProtos.Tree.Builder.class);
      }

      // Construct using com.github.kornilova_l.protos.TreeProtos.Tree.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCallsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        duration_ = 0L;

        startTime_ = 0L;

        threadId_ = 0L;

        if (callsBuilder_ == null) {
          calls_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          callsBuilder_.clear();
        }
        depth_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.kornilova_l.protos.TreeProtos.internal_static_com_github_kornilova_l_protos_Tree_descriptor;
      }

      public com.github.kornilova_l.protos.TreeProtos.Tree getDefaultInstanceForType() {
        return com.github.kornilova_l.protos.TreeProtos.Tree.getDefaultInstance();
      }

      public com.github.kornilova_l.protos.TreeProtos.Tree build() {
        com.github.kornilova_l.protos.TreeProtos.Tree result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.kornilova_l.protos.TreeProtos.Tree buildPartial() {
        com.github.kornilova_l.protos.TreeProtos.Tree result = new com.github.kornilova_l.protos.TreeProtos.Tree(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.duration_ = duration_;
        result.startTime_ = startTime_;
        result.threadId_ = threadId_;
        if (callsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            calls_ = java.util.Collections.unmodifiableList(calls_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.calls_ = calls_;
        } else {
          result.calls_ = callsBuilder_.build();
        }
        result.depth_ = depth_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.kornilova_l.protos.TreeProtos.Tree) {
          return mergeFrom((com.github.kornilova_l.protos.TreeProtos.Tree)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.kornilova_l.protos.TreeProtos.Tree other) {
        if (other == com.github.kornilova_l.protos.TreeProtos.Tree.getDefaultInstance()) return this;
        if (other.getDuration() != 0L) {
          setDuration(other.getDuration());
        }
        if (other.getStartTime() != 0L) {
          setStartTime(other.getStartTime());
        }
        if (other.getThreadId() != 0L) {
          setThreadId(other.getThreadId());
        }
        if (callsBuilder_ == null) {
          if (!other.calls_.isEmpty()) {
            if (calls_.isEmpty()) {
              calls_ = other.calls_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureCallsIsMutable();
              calls_.addAll(other.calls_);
            }
            onChanged();
          }
        } else {
          if (!other.calls_.isEmpty()) {
            if (callsBuilder_.isEmpty()) {
              callsBuilder_.dispose();
              callsBuilder_ = null;
              calls_ = other.calls_;
              bitField0_ = (bitField0_ & ~0x00000008);
              callsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCallsFieldBuilder() : null;
            } else {
              callsBuilder_.addAllMessages(other.calls_);
            }
          }
        }
        if (other.getDepth() != 0) {
          setDepth(other.getDepth());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.kornilova_l.protos.TreeProtos.Tree parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.kornilova_l.protos.TreeProtos.Tree) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long duration_ ;
      /**
       * <code>int64 duration = 1;</code>
       */
      public long getDuration() {
        return duration_;
      }
      /**
       * <code>int64 duration = 1;</code>
       */
      public Builder setDuration(long value) {
        
        duration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 duration = 1;</code>
       */
      public Builder clearDuration() {
        
        duration_ = 0L;
        onChanged();
        return this;
      }

      private long startTime_ ;
      /**
       * <pre>
       * only for trees which save original call structure
       * </pre>
       *
       * <code>int64 startTime = 2;</code>
       */
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <pre>
       * only for trees which save original call structure
       * </pre>
       *
       * <code>int64 startTime = 2;</code>
       */
      public Builder setStartTime(long value) {
        
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * only for trees which save original call structure
       * </pre>
       *
       * <code>int64 startTime = 2;</code>
       */
      public Builder clearStartTime() {
        
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private long threadId_ ;
      /**
       * <pre>
       * only for trees which save original call structure
       * </pre>
       *
       * <code>int64 threadId = 3;</code>
       */
      public long getThreadId() {
        return threadId_;
      }
      /**
       * <pre>
       * only for trees which save original call structure
       * </pre>
       *
       * <code>int64 threadId = 3;</code>
       */
      public Builder setThreadId(long value) {
        
        threadId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * only for trees which save original call structure
       * </pre>
       *
       * <code>int64 threadId = 3;</code>
       */
      public Builder clearThreadId() {
        
        threadId_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.github.kornilova_l.protos.TreeProtos.Tree.Call> calls_ =
        java.util.Collections.emptyList();
      private void ensureCallsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          calls_ = new java.util.ArrayList<com.github.kornilova_l.protos.TreeProtos.Tree.Call>(calls_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.kornilova_l.protos.TreeProtos.Tree.Call, com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder, com.github.kornilova_l.protos.TreeProtos.Tree.CallOrBuilder> callsBuilder_;

      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
       */
      public java.util.List<com.github.kornilova_l.protos.TreeProtos.Tree.Call> getCallsList() {
        if (callsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(calls_);
        } else {
          return callsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
       */
      public int getCallsCount() {
        if (callsBuilder_ == null) {
          return calls_.size();
        } else {
          return callsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
       */
      public com.github.kornilova_l.protos.TreeProtos.Tree.Call getCalls(int index) {
        if (callsBuilder_ == null) {
          return calls_.get(index);
        } else {
          return callsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
       */
      public Builder setCalls(
          int index, com.github.kornilova_l.protos.TreeProtos.Tree.Call value) {
        if (callsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCallsIsMutable();
          calls_.set(index, value);
          onChanged();
        } else {
          callsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
       */
      public Builder setCalls(
          int index, com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder builderForValue) {
        if (callsBuilder_ == null) {
          ensureCallsIsMutable();
          calls_.set(index, builderForValue.build());
          onChanged();
        } else {
          callsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
       */
      public Builder addCalls(com.github.kornilova_l.protos.TreeProtos.Tree.Call value) {
        if (callsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCallsIsMutable();
          calls_.add(value);
          onChanged();
        } else {
          callsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
       */
      public Builder addCalls(
          int index, com.github.kornilova_l.protos.TreeProtos.Tree.Call value) {
        if (callsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCallsIsMutable();
          calls_.add(index, value);
          onChanged();
        } else {
          callsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
       */
      public Builder addCalls(
          com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder builderForValue) {
        if (callsBuilder_ == null) {
          ensureCallsIsMutable();
          calls_.add(builderForValue.build());
          onChanged();
        } else {
          callsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
       */
      public Builder addCalls(
          int index, com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder builderForValue) {
        if (callsBuilder_ == null) {
          ensureCallsIsMutable();
          calls_.add(index, builderForValue.build());
          onChanged();
        } else {
          callsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
       */
      public Builder addAllCalls(
          java.lang.Iterable<? extends com.github.kornilova_l.protos.TreeProtos.Tree.Call> values) {
        if (callsBuilder_ == null) {
          ensureCallsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, calls_);
          onChanged();
        } else {
          callsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
       */
      public Builder clearCalls() {
        if (callsBuilder_ == null) {
          calls_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          callsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
       */
      public Builder removeCalls(int index) {
        if (callsBuilder_ == null) {
          ensureCallsIsMutable();
          calls_.remove(index);
          onChanged();
        } else {
          callsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
       */
      public com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder getCallsBuilder(
          int index) {
        return getCallsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
       */
      public com.github.kornilova_l.protos.TreeProtos.Tree.CallOrBuilder getCallsOrBuilder(
          int index) {
        if (callsBuilder_ == null) {
          return calls_.get(index);  } else {
          return callsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
       */
      public java.util.List<? extends com.github.kornilova_l.protos.TreeProtos.Tree.CallOrBuilder> 
           getCallsOrBuilderList() {
        if (callsBuilder_ != null) {
          return callsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(calls_);
        }
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
       */
      public com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder addCallsBuilder() {
        return getCallsFieldBuilder().addBuilder(
            com.github.kornilova_l.protos.TreeProtos.Tree.Call.getDefaultInstance());
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
       */
      public com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder addCallsBuilder(
          int index) {
        return getCallsFieldBuilder().addBuilder(
            index, com.github.kornilova_l.protos.TreeProtos.Tree.Call.getDefaultInstance());
      }
      /**
       * <code>repeated .com.github.kornilova_l.protos.Tree.Call calls = 4;</code>
       */
      public java.util.List<com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder> 
           getCallsBuilderList() {
        return getCallsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.kornilova_l.protos.TreeProtos.Tree.Call, com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder, com.github.kornilova_l.protos.TreeProtos.Tree.CallOrBuilder> 
          getCallsFieldBuilder() {
        if (callsBuilder_ == null) {
          callsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.github.kornilova_l.protos.TreeProtos.Tree.Call, com.github.kornilova_l.protos.TreeProtos.Tree.Call.Builder, com.github.kornilova_l.protos.TreeProtos.Tree.CallOrBuilder>(
                  calls_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          calls_ = null;
        }
        return callsBuilder_;
      }

      private int depth_ ;
      /**
       * <code>uint32 depth = 5;</code>
       */
      public int getDepth() {
        return depth_;
      }
      /**
       * <code>uint32 depth = 5;</code>
       */
      public Builder setDepth(int value) {
        
        depth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 depth = 5;</code>
       */
      public Builder clearDepth() {
        
        depth_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.github.kornilova_l.protos.Tree)
    }

    // @@protoc_insertion_point(class_scope:com.github.kornilova_l.protos.Tree)
    private static final com.github.kornilova_l.protos.TreeProtos.Tree DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.kornilova_l.protos.TreeProtos.Tree();
    }

    public static com.github.kornilova_l.protos.TreeProtos.Tree getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Tree>
        PARSER = new com.google.protobuf.AbstractParser<Tree>() {
      public Tree parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Tree(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Tree> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Tree> getParserForType() {
      return PARSER;
    }

    public com.github.kornilova_l.protos.TreeProtos.Tree getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_kornilova_l_protos_Tree_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_kornilova_l_protos_Tree_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_kornilova_l_protos_Tree_Call_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_kornilova_l_protos_Tree_Call_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(com/github/kornilova_l/protos/tree.pro" +
      "to\022\035com.github.kornilova_l.protos\032)com/g" +
      "ithub/kornilova_l/protos/event.proto\"\263\003\n" +
      "\004Tree\022\020\n\010duration\030\001 \001(\003\022\021\n\tstartTime\030\002 \001" +
      "(\003\022\020\n\010threadId\030\003 \001(\003\0227\n\005calls\030\004 \003(\0132(.co" +
      "m.github.kornilova_l.protos.Tree.Call\022\r\n" +
      "\005depth\030\005 \001(\r\032\253\002\n\004Call\022\020\n\010duration\030\001 \001(\003\022" +
      "9\n\005enter\030\002 \001(\0132*.com.github.kornilova_l." +
      "protos.Event.Enter\0229\n\004exit\030\003 \001(\0132).com.g" +
      "ithub.kornilova_l.protos.Event.ExitH\000\022C\n",
      "\texception\030\004 \001(\0132..com.github.kornilova_" +
      "l.protos.Event.ExceptionH\000\022\021\n\tstartTime\030" +
      "\005 \001(\003\0227\n\005calls\030\006 \003(\0132(.com.github.kornil" +
      "ova_l.protos.Tree.CallB\n\n\010exitInfoB\014B\nTr" +
      "eeProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.kornilova_l.protos.EventProtos.getDescriptor(),
        }, assigner);
    internal_static_com_github_kornilova_l_protos_Tree_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_kornilova_l_protos_Tree_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_kornilova_l_protos_Tree_descriptor,
        new java.lang.String[] { "Duration", "StartTime", "ThreadId", "Calls", "Depth", });
    internal_static_com_github_kornilova_l_protos_Tree_Call_descriptor =
      internal_static_com_github_kornilova_l_protos_Tree_descriptor.getNestedTypes().get(0);
    internal_static_com_github_kornilova_l_protos_Tree_Call_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_kornilova_l_protos_Tree_Call_descriptor,
        new java.lang.String[] { "Duration", "Enter", "Exit", "Exception", "StartTime", "Calls", "ExitInfo", });
    com.github.kornilova_l.protos.EventProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
